add_newline = false

# A minimal left prompt
format = """$directory$git_branch$git_status$status$character"""

# no right prompt
right_format = ""

# Timeout for commands executed by starship (in milliseconds)
command_timeout=2000

[character]
success_symbol = "[❱](green)"
error_symbol = "[❱](red)"
vicmd_symbol = "[❰](cyan)"

[directory]
style = "bold green"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = '[$branch]($style)'
style = 'bold purple'

[git_status]
style = "cyan"
format = "[( $all_status$ahead_behind )]($style)"

[line_break]
disabled = true

[status]
disabled = false
pipestatus = true
format = '[$symbol$int]($style)'
symbol = '✘'
pipestatus_format = '\[$pipestatus\]($style)'
